//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Product
{
    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public string ProductDescp { get; set; }
    public string ProductType { get; set; }
    public string ProductSize { get; set; }
    public string ProductCategory { get; set; }
    public Nullable<decimal> ProductPrice { get; set; }
    public byte[] Product_Image_binary { get; set; }
    public byte[] Product_Image_binary2 { get; set; }
    public byte[] Product_Image_binary3 { get; set; }
    public byte[] Product_Image_binary4 { get; set; }
    public string Product_Image_Name1 { get; set; }
    public string Product_Image_Name2 { get; set; }
    public string Product_Image_Name3 { get; set; }
    public string Product_Image_Name4 { get; set; }
}
